/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface SchemaProjects {
  id?: number;
  id_supervisors?: number;
  id_admins: number;
  image: string;
  name: string;
  name_company: string;
  contract_number: number;
  contract_date: string;
  activity: string;
  obstacles: string;
  status: string;
  progress: number;
  fund_source: string;
  fiscal_year: string;
  coordinate: number[];
  createdAt?: string;
  updatedAt?: string;
}
