/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface SchemaSupervisors {
  id: number;
  username: string;
  password: string;
  role: "supervisors";
  name: string;
  email: string;
  createdAt: string;
  updatedAt: string;
}
