/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface SchemaTasks {
  id?: number;
  id_projects: number;
  order: number;
  note: string;
  done: boolean;
  createdAt?: string;
  updatedAt?: string;
}
